# @package _global_
defaults:
  - /dataset/Nuscenes_map_cache_box

# this config only remove object items on map construction
# map size: (8, 200, 200)

dataset:
  dataset_type: NuScenesTDataset
  dataset_process_root: ../data/nuscenes_mmdet3d-t-keyframes/
  start_on_keyframe: true
 
  data:
    train:
      video_length: ${model.video_length}
      start_on_keyframe: ${dataset.start_on_keyframe}
    val:
      video_length: ${model.video_length}
      start_on_keyframe: ${dataset.start_on_keyframe}
    test:
      video_length: ${model.video_length}
      start_on_keyframe: ${dataset.start_on_keyframe}
