# @package _global_
defaults:
  - /dataset/Nuscenes_map_cache_box
  # - /runner/8gpus
  - model: ../../model/SDv1.5mv_rawbox
  - _self_  # make sure override

# based on rawbox1.4
task_id: 0.2.0
runner:
  validation_show_box: true
  enable_xformers_memory_efficient_attention: true  # always need this.

model:
  bbox_mode: 'all-xyz'
  bbox_view_shared: false
  controlnet:
    bbox_embedder_param:
      minmax_normalize: false
